# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/workspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/workspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/workspace/CMakeFiles /opt/workspace//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/workspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named messenger_idl

# Build rule for target.
messenger_idl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 messenger_idl
.PHONY : messenger_idl

# fast build rule for target.
messenger_idl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_idl.dir/build.make CMakeFiles/messenger_idl.dir/build
.PHONY : messenger_idl/fast

#=============================================================================
# Target rules for targets named _opendds_codegen_1_for_messenger_idl

# Build rule for target.
_opendds_codegen_1_for_messenger_idl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _opendds_codegen_1_for_messenger_idl
.PHONY : _opendds_codegen_1_for_messenger_idl

# fast build rule for target.
_opendds_codegen_1_for_messenger_idl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_opendds_codegen_1_for_messenger_idl.dir/build.make CMakeFiles/_opendds_codegen_1_for_messenger_idl.dir/build
.PHONY : _opendds_codegen_1_for_messenger_idl/fast

#=============================================================================
# Target rules for targets named publisher

# Build rule for target.
publisher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 publisher
.PHONY : publisher

# fast build rule for target.
publisher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/build
.PHONY : publisher/fast

#=============================================================================
# Target rules for targets named subscriber

# Build rule for target.
subscriber: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 subscriber
.PHONY : subscriber

# fast build rule for target.
subscriber/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/build
.PHONY : subscriber/fast

DataReaderListenerImpl.o: DataReaderListenerImpl.cpp.o
.PHONY : DataReaderListenerImpl.o

# target to build an object file
DataReaderListenerImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/DataReaderListenerImpl.cpp.o
.PHONY : DataReaderListenerImpl.cpp.o

DataReaderListenerImpl.i: DataReaderListenerImpl.cpp.i
.PHONY : DataReaderListenerImpl.i

# target to preprocess a source file
DataReaderListenerImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/DataReaderListenerImpl.cpp.i
.PHONY : DataReaderListenerImpl.cpp.i

DataReaderListenerImpl.s: DataReaderListenerImpl.cpp.s
.PHONY : DataReaderListenerImpl.s

# target to generate assembly for a file
DataReaderListenerImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/DataReaderListenerImpl.cpp.s
.PHONY : DataReaderListenerImpl.cpp.s

Publisher.o: Publisher.cpp.o
.PHONY : Publisher.o

# target to build an object file
Publisher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/Publisher.cpp.o
.PHONY : Publisher.cpp.o

Publisher.i: Publisher.cpp.i
.PHONY : Publisher.i

# target to preprocess a source file
Publisher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/Publisher.cpp.i
.PHONY : Publisher.cpp.i

Publisher.s: Publisher.cpp.s
.PHONY : Publisher.s

# target to generate assembly for a file
Publisher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/Publisher.cpp.s
.PHONY : Publisher.cpp.s

Subscriber.o: Subscriber.cpp.o
.PHONY : Subscriber.o

# target to build an object file
Subscriber.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/Subscriber.cpp.o
.PHONY : Subscriber.cpp.o

Subscriber.i: Subscriber.cpp.i
.PHONY : Subscriber.i

# target to preprocess a source file
Subscriber.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/Subscriber.cpp.i
.PHONY : Subscriber.cpp.i

Subscriber.s: Subscriber.cpp.s
.PHONY : Subscriber.s

# target to generate assembly for a file
Subscriber.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/Subscriber.cpp.s
.PHONY : Subscriber.cpp.s

opendds_generated/messenger_idl/MessengerC.o: opendds_generated/messenger_idl/MessengerC.cpp.o
.PHONY : opendds_generated/messenger_idl/MessengerC.o

# target to build an object file
opendds_generated/messenger_idl/MessengerC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_idl.dir/build.make CMakeFiles/messenger_idl.dir/opendds_generated/messenger_idl/MessengerC.cpp.o
.PHONY : opendds_generated/messenger_idl/MessengerC.cpp.o

opendds_generated/messenger_idl/MessengerC.i: opendds_generated/messenger_idl/MessengerC.cpp.i
.PHONY : opendds_generated/messenger_idl/MessengerC.i

# target to preprocess a source file
opendds_generated/messenger_idl/MessengerC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_idl.dir/build.make CMakeFiles/messenger_idl.dir/opendds_generated/messenger_idl/MessengerC.cpp.i
.PHONY : opendds_generated/messenger_idl/MessengerC.cpp.i

opendds_generated/messenger_idl/MessengerC.s: opendds_generated/messenger_idl/MessengerC.cpp.s
.PHONY : opendds_generated/messenger_idl/MessengerC.s

# target to generate assembly for a file
opendds_generated/messenger_idl/MessengerC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_idl.dir/build.make CMakeFiles/messenger_idl.dir/opendds_generated/messenger_idl/MessengerC.cpp.s
.PHONY : opendds_generated/messenger_idl/MessengerC.cpp.s

opendds_generated/messenger_idl/MessengerTypeSupportC.o: opendds_generated/messenger_idl/MessengerTypeSupportC.cpp.o
.PHONY : opendds_generated/messenger_idl/MessengerTypeSupportC.o

# target to build an object file
opendds_generated/messenger_idl/MessengerTypeSupportC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_idl.dir/build.make CMakeFiles/messenger_idl.dir/opendds_generated/messenger_idl/MessengerTypeSupportC.cpp.o
.PHONY : opendds_generated/messenger_idl/MessengerTypeSupportC.cpp.o

opendds_generated/messenger_idl/MessengerTypeSupportC.i: opendds_generated/messenger_idl/MessengerTypeSupportC.cpp.i
.PHONY : opendds_generated/messenger_idl/MessengerTypeSupportC.i

# target to preprocess a source file
opendds_generated/messenger_idl/MessengerTypeSupportC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_idl.dir/build.make CMakeFiles/messenger_idl.dir/opendds_generated/messenger_idl/MessengerTypeSupportC.cpp.i
.PHONY : opendds_generated/messenger_idl/MessengerTypeSupportC.cpp.i

opendds_generated/messenger_idl/MessengerTypeSupportC.s: opendds_generated/messenger_idl/MessengerTypeSupportC.cpp.s
.PHONY : opendds_generated/messenger_idl/MessengerTypeSupportC.s

# target to generate assembly for a file
opendds_generated/messenger_idl/MessengerTypeSupportC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_idl.dir/build.make CMakeFiles/messenger_idl.dir/opendds_generated/messenger_idl/MessengerTypeSupportC.cpp.s
.PHONY : opendds_generated/messenger_idl/MessengerTypeSupportC.cpp.s

opendds_generated/messenger_idl/MessengerTypeSupportImpl.o: opendds_generated/messenger_idl/MessengerTypeSupportImpl.cpp.o
.PHONY : opendds_generated/messenger_idl/MessengerTypeSupportImpl.o

# target to build an object file
opendds_generated/messenger_idl/MessengerTypeSupportImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_idl.dir/build.make CMakeFiles/messenger_idl.dir/opendds_generated/messenger_idl/MessengerTypeSupportImpl.cpp.o
.PHONY : opendds_generated/messenger_idl/MessengerTypeSupportImpl.cpp.o

opendds_generated/messenger_idl/MessengerTypeSupportImpl.i: opendds_generated/messenger_idl/MessengerTypeSupportImpl.cpp.i
.PHONY : opendds_generated/messenger_idl/MessengerTypeSupportImpl.i

# target to preprocess a source file
opendds_generated/messenger_idl/MessengerTypeSupportImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_idl.dir/build.make CMakeFiles/messenger_idl.dir/opendds_generated/messenger_idl/MessengerTypeSupportImpl.cpp.i
.PHONY : opendds_generated/messenger_idl/MessengerTypeSupportImpl.cpp.i

opendds_generated/messenger_idl/MessengerTypeSupportImpl.s: opendds_generated/messenger_idl/MessengerTypeSupportImpl.cpp.s
.PHONY : opendds_generated/messenger_idl/MessengerTypeSupportImpl.s

# target to generate assembly for a file
opendds_generated/messenger_idl/MessengerTypeSupportImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_idl.dir/build.make CMakeFiles/messenger_idl.dir/opendds_generated/messenger_idl/MessengerTypeSupportImpl.cpp.s
.PHONY : opendds_generated/messenger_idl/MessengerTypeSupportImpl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... _opendds_codegen_1_for_messenger_idl"
	@echo "... messenger_idl"
	@echo "... publisher"
	@echo "... subscriber"
	@echo "... DataReaderListenerImpl.o"
	@echo "... DataReaderListenerImpl.i"
	@echo "... DataReaderListenerImpl.s"
	@echo "... Publisher.o"
	@echo "... Publisher.i"
	@echo "... Publisher.s"
	@echo "... Subscriber.o"
	@echo "... Subscriber.i"
	@echo "... Subscriber.s"
	@echo "... opendds_generated/messenger_idl/MessengerC.o"
	@echo "... opendds_generated/messenger_idl/MessengerC.i"
	@echo "... opendds_generated/messenger_idl/MessengerC.s"
	@echo "... opendds_generated/messenger_idl/MessengerTypeSupportC.o"
	@echo "... opendds_generated/messenger_idl/MessengerTypeSupportC.i"
	@echo "... opendds_generated/messenger_idl/MessengerTypeSupportC.s"
	@echo "... opendds_generated/messenger_idl/MessengerTypeSupportImpl.o"
	@echo "... opendds_generated/messenger_idl/MessengerTypeSupportImpl.i"
	@echo "... opendds_generated/messenger_idl/MessengerTypeSupportImpl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

